dirs:
  .:
    lock_branch_target: all
    tags: []
    workspaces:
      iac_infra_runtime_dev:
        tags:
        - dir:.
        - runtime
        - use1-dev
        - workspace:iac_infra_runtime_dev
        when_modified:
          autoapply: false
          autoplan: true
          file_patterns:
          - '**/*.tf'
          - '!k8s/**'
          - tfvars/iac_infra_runtime_dev.tfvars
      iac_infra_runtime_prod:
        tags:
        - dir:.
        - runtime
        - use1-prod
        - workspace:iac_infra_runtime_prod
        when_modified:
          autoapply: false
          autoplan: true
          file_patterns:
          - '**/*.tf'
          - '!k8s/**'
          - tfvars/iac_infra_runtime_prod.tfvars
  k8s:
    tags: []
    workspaces:
      iac_infra_k8s_dev2_use1:
        tags:
        - dir:k8s
        - k8s
        - use1-dev
        - workspace:iac_infra_k8s_dev2_use1
        when_modified:
          autoapply: false
          autoplan: true
          depends_on:
            tag_query: k8s_clusters in outputs:. and workspace:iac_infra_runtime_dev
          file_patterns:
          - k8s/*.tf
          - k8s/tfvars/iac_infra_k8s_dev2_use1.tfvars
      iac_infra_k8s_dev_national_man:
        tags:
        - dir:k8s
        - k8s
        - use1-dev
        - workspace:iac_infra_k8s_dev_national_man
        when_modified:
          autoapply: false
          autoplan: true
          depends_on:
            tag_query: k8s_clusters in outputs:. and workspace:iac_infra_runtime_dev
          file_patterns:
          - k8s/*.tf
          - k8s/tfvars/iac_infra_k8s_dev_national_man.tfvars
      iac_infra_k8s_prod1_use1:
        tags:
        - dir:k8s
        - k8s
        - use1-prod
        - workspace:iac_infra_k8s_prod1_use1
        when_modified:
          autoapply: false
          autoplan: true
          depends_on:
            tag_query: k8s_clusters in outputs:. and workspace:iac_infra_runtime_prod
          file_patterns:
          - k8s/*.tf
          - k8s/tfvars/iac_infra_k8s_prod1_use1.tfvars
  k8s/tfvars:
    lock_branch_target: all
    tags: []
    workspaces:
      default:
        tags:
        - dir:k8s/tfvars
        - workspace:default
        when_modified:
          autoapply: false
          autoplan: true
          file_patterns: []
  tfvars:
    lock_branch_target: all
    tags: []
    workspaces:
      default:
        tags:
        - dir:tfvars
        - workspace:default
        when_modified:
          autoapply: false
          autoplan: true
          file_patterns: []
engine:
  name: terraform
  outputs:
    collect: true
  version: 1.11.1
stacks:
  names:
    dev:
      stacks:
      - use1-dev
    prod:
      rules:
        apply_after:
        - dev
      stacks:
      - use1-prod
    use1-dev:
      tag_query: use1-dev
    use1-prod:
      tag_query: use1-prod
workflows:
- apply:
  - type: init
  - type: apply
  engine:
    name: terraform
    outputs:
      collect: true
    version: 1.11.1
  plan:
  - type: init
  - extra_args:
    - -lock=false
    - -var-file=tfvars/${TERRATEAM_WORKSPACE}.tfvars
    type: plan
  tag_query: ''
