name: 'Terrateam Webhook Proxy'
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, closed, edited]
  issue_comment:
    types: [created]
  push:
permissions: {}
jobs:
  forward:
    runs-on: ubuntu-latest
    steps:
      - uses: stategraph/action-webhook-proxy@2419-fix-forwarding
        with:
          terrateam-url: https://devious-logical-scorpion.tunnel.terrateam.dev
          webhook-secret: thisisatestofouractionproxy
          installation-id: 55143082